### ISSUE TITLE
questions for dataset

### ISSUE THREAD

**Issue by zhouak47** [sled-group/navchat#1]
Thanks  for your great job. I meet some problems when i try to get hm3d dataset.  can you tell me how to create the soft link ? I am looking forward to your reply .thanks

**Comment by zhouak47** [comment]
I also have a question  about HM3D.I  have download all HM3D v0.2 files. Are all files needed? Can you tell me which files of HM3D are placeed under  scene_datasets/hm3d_v0.2,thanks.

**Comment by YinpeiDai** [comment]
Hi, thanks for your interest in our work. we follows the same practice as Habitat to create softlink.
you can use `ln -s <real_path_of_hm3d_v0.2 >  data/scene_datasets/hm3d_v0.2 ` to do this

We chooses 10 scenes from HM3Dv0.2, `4ok3usBNeis, MHPLjHsuG27, mL8ThkuaVTM, QaLdnwvtxbs, TEEsavR23oF, qyAac8rV8Zk, h1zeeAwLh9Z, cvZr5TUy5C5, LT9Jq6dN3Ea, y9hTuugGdiq` from val set.  I also updated this in the readme. Thanks!
